codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "40...90"

  status:
    project:
      default:
        target: 0%
        threshold: 0%
        if_ci_failed: error
        only_pulls: true
    patch: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
