language: go

go:
  - 1.11.x
  - tip

addons:
  mariadb: '10.1'

sudo: false

env:
  - GO111MODULE=on

install:
  - go install github.com/mattn/go-sqlite3

before_script:
  - mysql -e 'CREATE DATABASE bartlett;'

script:
  - go test -coverprofile=coverage-unit.txt -v $(go list ./... | grep -v mariadb)
  - go test -coverprofile=coverage-mariadb.txt -v ./mariadb -dsn travis@/bartlett
  - grep -v "mode:" coverage-mariadb.txt | cat coverage-unit.txt - > coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
