language: go

go:
  - 1.11.x
  - tip

addons:
  mariadb: '10.1'

sudo: false

install:
  - go get -t -v ./...
  - go install github.com/mattn/go-sqlite3

before_script:
  - mysql -e 'CREATE DATABASE bartlett;'

script:
  - go test -tags sqlite3
  - go test -tags mariadb -args -dsn travis@/bartlett
