language: go

go:
  - 1.11.x
  - tip

addons:
  mariadb: '10.1'

sudo: false

env:
  - GO111MODULE=on

install:
  - go get ./...
  - go install github.com/mattn/go-sqlite3

before_script:
  - mysql -e 'CREATE DATABASE bartlett;'

script:
  - go test -v ./sqlite3
  - go test -v ./mariadb -dsn travis@/bartlett
  - go test -v $(go list ./... | grep -v mariadb | grep -v sqlite3)
